name: 'Fianu Capture Blob Evidence'
description: 'This action captures evidence using the Fianu CLI.'
inputs:
  fianu-host:
    description: "Fianu Host URL"
    required: true
    default: "https://app.fianu.io"
  fianu-cli-version:
    description: "Fianu CLI Version to Use"
    required: true
    default: "1.9.11"
  fianu-app-code:
    description: "Fianu App Code"
    required: true
  fianu-client-id:
    description: "Fianu Client ID"
    required: true
  fianu-client-secret:
    description: "Fianu Client Secret"
    required: true
  fianu-username:
    description: "Fianu Username (Optional)"
    required: false
  fianu-service-account:
    description: 'The Fianu service account provided to your organization to perform keyless signing.'
    required: true
  audience:
    description: 'Specifies the identity token audience to use when creating an identity token to authenticate with Fianu.'
    required: false
    default: sigstore
  evidence:
    description: 'The path to the (blob) evidence to sign and capture.'
    required: true
  evidence-uri:
    description: 'The URI of the resource to associate with the evidence.'
    required: false
    default: ''
  evidence-source:
    description: 'The source of the evidence.'
    required: true
  evidence-type:
    description: 'The type of evidence to capture.'
    required: true
runs:
  using: "composite"
  steps:
    # Authentication Google Cloud CLI
    # Reference: https://github.com/google-github-actions/auth
    - name: Google Cloud Authentication Setup
      id: gcloud_auth
      uses: google-github-actions/auth@v2
      with:
        token_format: id_token
        id_token_audience: ${{ inputs.audience }}
        id_token_include_email: true
        workload_identity_provider: 'projects/68661080711/locations/global/workloadIdentityPools/fianu-github-actions/providers/github'
        service_account: ${{ inputs.fianu-service-account }}

    # Google Cloud CLI Installation
    - name: Google Cloud CLI Installation
      id: setup_gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: 'projects/68661080711/locations/global/workloadIdentityPools/fianu-github-actions/providers/github'

    # Install Cosign CLI
    # Reference: https://github.com/sigstore/cosign-installer
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.5.0

    # Sign and Capture SBOM Evidence
    - name: Cosign Sign Blob and Capture SBOM Evidence
      shell: bash
      env:
        FIANU_HOST: ${{ inputs.fianu-host }}
        FIANU_CLIENT_ID: ${{ inputs.fianu-client-id }}
        FIANU_CLIENT_SECRET: ${{ inputs.fianu-client-secret }}
        FIANU_APP_CODE: ${{ inputs.fianu-app-code }}
        FIANU_USERNAME: ${{ inputs.fianu-username }}
        FIANU_VERSION: ${{ inputs.fianu-cli-version }}
      run: |-
        # Initialize Cosign with the Fianu Mirror and Root
        cosign initialize \
          --mirror "${{ env.FIANU_HOST }}/ledger/root" \
          --root "${{ env.FIANU_HOST }}/ledger/root/root.json"

        # Sign the SBOM with Cosign, generate a Rekor Bundle, and output the Digest
        cosign sign-blob --yes \
          "${{ inputs.evidence }}" \
          --bundle "bundle.json" \
          --rekor-url "${{ env.FIANU_HOST }}" \
          --identity-token=${{ steps.gcloud_auth.outputs.id_token }} \
          --fulcio-url "${{ env.FIANU_HOST }}/ledger/fulcio"

        # Capture the Generated Bundle with Fianu
        fianu capture evidence \
          --input bundle.json \
          --type ${{ inputs.evidence-type }}  \
          --source ${{ inputs.evidence-source }} \
          --resource-uri ${{ inputs.evidence-uri }} $format_option
