name: secure-fianu-agent
description: Sets up Fianu CLI on GitHub Actions runners
inputs:
  version:
    description: Version of Fianu Agent to install
    required: false
    default: 1.0.5
runs:
  using: node20
  main: agent/dist/index.js
  post: "agent/dist/post/index.js"