name: Tests

on:
  push:
    branches:
    - main
    - testing
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  deptest:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [1.2.2, 1.9.0, 1.9.1, 1.9.2, 1.9.4, 1.9.5, 1.9.6, 1.9.7, 1.9.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup gh
        uses: ./
        with:
          version: ${{ matrix.version }}

      - name: Test CLI
        run: |-
          fianu
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [1.3.0]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup gh
      uses: ./
      with:
        version: ${{ matrix.version }}

    - name: Test CLI
      run: |-
        fianu
