name: Test Root Init

on:
  push:
    branches:
      - main
      - feature/add-windows-init-tests
  pull_request:

permissions:
  id-token: write
  contents: write
  packages: write
  actions: write

jobs:
  test_windows:
    defaults:
      run:
        shell: pwsh
    name: Test Windows
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
        version: [ 1.9.40-1-beta ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup gh
        uses: ./
        with:
          version: ${{ matrix.version }}

      - name: Test CLI Windows
        shell: pwsh
        env:
          FIANU_CLIENT_ID: ${{ secrets.FIANU_CLIENT_ID }}
          FIANU_CLIENT_SECRET: ${{ secrets.FIANU_CLIENT_SECRET }}
          FIANU_HOST: ${{ secrets.FIANU_HOST }}
        run: |-
          # Run the Fianu CLI and capture stdout and stderr
          $fianuOutput = & fianu root init --debug 2>&1
          # Write to GitHub summary (optional)
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "`n### Fianu Output`n"
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "``````"
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "$fianuOutput"
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "``````"
          # Also write to console log
          $dirList = Get-ChildItem -Recurse | Select-Object FullName | Out-String
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "### Directory Listing`n``````"
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value $dirList.Trim()
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "`n``````"

  test_linux:
    name: Test
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest-large, macos-13, macos-14 ]
        version: [ 1.9.40-1-beta ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup gh
        uses: ./
        with:
          version: ${{ matrix.version }}

      - name: Test CLI Linux
        shell: bash
        env:
          FIANU_CLIENT_ID: ${{ secrets.FIANU_CLIENT_ID }}
          FIANU_CLIENT_SECRET: ${{ secrets.FIANU_CLIENT_SECRET }}
          FIANU_HOST: ${{ secrets.FIANU_HOST }}
        run: |-
          uname -s | tr '[:upper:]' '[:lower:]'
          fianu root init
