name: Tests

on:
  push:
    branches:
      - main
      - feature/add-windows-init-tests
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest-large, macos-13, macos-14 ]
        version: [ 1.9.40-1-beta ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup gh
        uses: ./
        with:
          version: ${{ matrix.version }}

      - name: Test CLI Linux
        if: startsWith(runner.os, 'Windows')
        shell: pwsh
        env:
          FIANU_CLIENT_ID: ${{ secrets.FIANU_CLIENT_ID }}
          FIANU_CLIENT_SECRET: ${{ secrets.FIANU_CLIENT_SECRET }}
          FIANU_HOST: ${{ secrets.FIANU_HOST }}
        run: |-
          uname -s | tr '[:upper:]' '[:lower:]'
          fianu root init

      - name: Test CLI Windows
        if: !startsWith(runner.os, 'Windows')
        env:
          FIANU_CLIENT_ID: ${{ secrets.FIANU_CLIENT_ID }}
          FIANU_CLIENT_SECRET: ${{ secrets.FIANU_CLIENT_SECRET }}
          FIANU_HOST: ${{ secrets.FIANU_HOST }}
        run: |-
          uname -s | tr '[:upper:]' '[:lower:]'
          fianu root init
