name: Test Root Init

on:
  push:
    branches:
      - main
      - feature/add-windows-init-tests
  pull_request:

jobs:
  test_windows:
    defaults:
      run:
        shell: pwsh
    name: Test Windows
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
        version: [ 1.9.39-1-beta ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup gh
        uses: ./
        with:
          version: ${{ matrix.version }}

      - name: Test CLI Windows
        shell: pwsh
        env:
          FIANU_CLIENT_ID: ${{ secrets.FIANU_CLIENT_ID }}
          FIANU_CLIENT_SECRET: ${{ secrets.FIANU_CLIENT_SECRET }}
          FIANU_HOST: ${{ secrets.FIANU_HOST }}
        run: |-
          # Capture only stdout from the command
          fianu root init
          
          # List current directory recursively
          $dirList = Get-ChildItem -Recurse | Select-Object FullName | Out-String
                  
          # Write directory listing to GitHub summary
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "### Directory Listing`n``````"
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value $dirList.Trim()
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "`n``````"